package.json, src/components/calendar/calendar.css, src/components/datepicker.js
You can now use `onDateChange` and `selected` props to control the datepicker, just like you would use `onChange` and `value` in an input element.
Also, it adds a default prop to `firstDayOfWeek` and a `z-index` to the calendar component.
The `state` of the datepicker is not updated when a new `selected` prop is provided.
When a new `selected` prop is provided, the datepicker recalculates its state.
**Checklist**:
=> Feature: Turning datepicker into a controlled component

package.json
Bug fix.
The change implemented on #13 added the `postinstall` script. However, it broke the installation of the library because there isn't a `date-fns-v2` folder in the files published to npm.
The `prepare` script does what the `postinstall` script did, but it only runs in development environment.
=> fix(package.json): Replacing `postinstall` for `prepare` script

src/components/datepicker.js
Bug fix.
When this component is used with libraries such as `react-final-form`, the validation doesn't work properly because the form library validates each input on blur, but the datepicker doesn't fire the event.
The prop `onBlur`, which defaults to an "empty function" is now fired, allowing such validations to work properly.
=> fix(datepicker): Firing the onBlur event passed as prop

src/index.d.ts
As per title - this seems to prevent TS compilation.
=> Update TypeScript definitions to remove duplicate definition

README.md, src/components/datepicker.js, stories/index.js
This PR is a feature. It adds `readOnly` as one of the supported `Form.Input` props.
It adds `readOnly` as one of the supported `Form.Input` props.
`readOnly` is not a supported prop of `Form.Input`. 
`readOnly` is now a supported prop of `Form.Input`.  
**Checklist**:
=> Add `readOnly` as a supported Form.Input prop

package.json, src/components/datepicker.js
This PR is a bug fix for issue https://github.com/arthurdenner/react-semantic-ui-datepickers/issues/41. It ensures the date picker is not shown if the field is marked as `readOnly`.
It ensures the date picker is not shown if the field is marked as `readOnly`.
Currently, when clicking on an input marked as `readOnly`, the date picker will still be displayed.
Now, when clicking on an input marked as `readOnly`, the date picker will no longer be displayed.
**Checklist**:
=> fix(datepicker): showCalendar no longer triggers if readOnly is true

CONTRIBUTING.md, src/types/index.ts
Bugfix. Missing implementation from #80.
We didn't add `ca-ES` as one of the possible values to the `locale` prop.
Now we have it.
PS: The instructions about how to add a locale were updated on the related issue.
**Checklist**:
=> fix(types): add Catalan locale key to options of locale prop

README.md, src/__tests__/datepicker.test.tsx, src/__tests__/utils.test.ts, src/components/calendar/calendar.tsx, src/index.tsx, src/pickers/basic.tsx, src/pickers/index.tsx, src/pickers/range.tsx, src/types/index.ts, src/utils.ts, stories/basic.stories.tsx, stories/range.stories.tsx
Feature. Closes #30.
Our component has a different API from the other components from React Semantic UI.
The main differences are:
- Components from RSUI have a prop named `onChange`;
- Components from RSUI have a prop named `value`;
- The signature for the `onChange` props on RSUI is: (event: SyntheticEvent, data: ComponentProps).
All the points mentioned above are addressed.
**Checklist**:
=> feat(datepicker): Rename props and update onChange signature

README.md, src/__tests__/datepicker.test.tsx, src/components/input.tsx, src/index.tsx, src/types/index.ts, stories/basic.stories.tsx
Introduce `datePickerOnly` to disable text input of dates and still allow the date to be selected from the date picker.
`readOnly` disables the text input and the date picker.
Add `datePickerOnly` to disable text input while still allowing the date to be selected via the date picker.
**Checklist**:
=> Add support for date picker only mode

README.md
This is to add to the documentation an example of react hook for usage and add clarity to how the date is retrieved with params `(event, date)` and displayed from property `value` via `data.value`
Closes #144.
=> added react hook usage to documentation for further clarity

README.md, src/__tests__/datepicker.test.tsx, src/index.tsx, src/types/index.ts
Feature. Closes #215.
`autoComplete` is not passed down to the DOM input.
The attribute is whitelisted, and therefore, applied to the DOM input.
**Checklist**:
=> feat(datepicker): support autoComplete prop

src/__tests__/datepicker.test.tsx, src/components/input.tsx, src/index.tsx
Bug fix. Closes #238.
The `onBlur` callback is fired automatically and in the wrong moments, e.g. selecting the first date on a range input.
The callback is fired manually and the focus on the input is also controlled.
**Checklist**:
=> fix(datepicker): fire onBlur callback properly

tsdx.config.js
Build fix.
`rollup-plugin-postcss` was updated and the new major version changes how the path for the CSS file is constructed. Therefore, we don't need to specify the `dist` folder anymore.
The build config is fixed.
**Checklist**:
=> fix(rollup): fix destination path for CSS file

package.json, src/__tests__/datepicker.test.tsx, src/index.tsx, stories/basic.stories.tsx
Bug fix. Closes #260.
`placeholder` prop is overridden with it's an empty string or `null`.
If the `placeholder` prop is different from `undefined`, it's applied. Otherwise, we use the `format` prop as placeholder.
**Checklist**:
=> fix(datepicker): allow empty string as placeholder

src/__tests__/datepicker.test.tsx, src/components/input.tsx
Bug fix.
When provided, the `id` prop is not applied on the `label`'s `htmlFor` attribute.
The `id` is applied and therefore, the label is now accessible.
**Checklist**:
=> fix(datepicker): apply id on label's htmlFor attribute

README.md, src/__tests__/datepicker.test.tsx, src/components/calendar/calendar.css, src/components/calendar/calendar.tsx, src/index.tsx, src/types/index.ts, stories/common.tsx, stories/index.stories.tsx
Feature. Closes #282.
No current behavior.
Through a new boolean prop, `inline`, the user can opt-in for a variant of the library without the input, and therefore, all the features related to it, e.g. clearable datepicker.
**Checklist**:
=> feat(datepicker): support inline variant without input

README.md, jest.setup.ts, package.json, src/__tests__/datepicker.test.tsx, src/components/icon.tsx, src/components/input.tsx, src/index.tsx, src/types/index.ts, stories/data.ts, stories/index.stories.tsx, yarn.lock
Feature. Closes #296.
- It's not possible to pass a custom component, we can only use values from SemanticUIReact;
- It's not possible to customize the clear icon, it always renders the `close` icon.
- It's possible to pass a custom component to the `icon` prop;
- It's possible to pass a value from SemanticUIReact or a custom component to the `clearIcon` prop.
**Checklist**:
=> feat: support custom icon and clearIcon props

README.md, src/index.tsx, src/types/index.ts
Feature. Closes #337.
No support for custom `className`.
`className` is supported and passed down to Semantic UI's Input, like when using `semantic-ui-react`.
**Checklist**:
=> feat(datepicker): support custom className and pass it to SUI's input

package.json, src/__tests__/_utils.tsx, src/__tests__/datepicker.test.tsx, src/__tests__/usecases.test.tsx, src/index.tsx, yarn.lock
Bug fix. Closes #334.
When the user types an invalid date, but input is updated but the `onChange` callback isn't fired.
The callback is properly fired.
**Checklist**:
=> fix(datepicker): fire onChange callback when typed date is invalid

.github/workflows/build.yml, src/__tests__/datepicker.test.tsx, src/__tests__/usecases.test.tsx, src/components/calendar/calendar.css, src/components/calendar/calendar.tsx, src/components/cell/cell.css, src/components/cell/cell.tsx, src/components/input.tsx, src/components/today-button.tsx, src/index.tsx, src/types/index.ts
Bug fixes related to #509 and #510.
It also fixes a few a11y issues:
- Dates and weekdays are now tabbable;
- Calendar is shown when input is focused through keyboard;
- Translated `aria-label`s are applied to back and forward buttons;
Check the linked issues.
For #509, `tabIndex` is now forwarded to the native `input` as in React Semantic UI does;
For #510, we correctly apply what's typed inside the input when leaving it.
**Checklist**:
=> fix(datepicker): fix onBlur, tabIndex and a11y issues

src/components/icon.tsx
Refactor. Related to [this comment](https://github.com/arthurdenner/react-semantic-ui-datepickers/issues/510#issuecomment-773857951).
When the input is focused, the content is selected. When the user presses `Tab`, we focus the clear button.
Focus the clear button is a bit unnecessary since the content is selected every time the input is focused, allowing the user to clear it by pressing `Backspace` or `Delete`.
**Checklist**:
=> refactor(datepicker): remove focus from clear button

package.json, src/__tests__/usecases.test.tsx, yarn.lock
Fix a long standing issue.
When a PR is created at the start or end of a month, the keyboard accessibility test fails because the relative last or next weeks can't be accessed.
By fixing the time with the `timekeeper` library, we can ensure the time will always be a valid one for performing the tests.
**Checklist**:
=> test: freeze time when testing keyboard accessibility

src/index.tsx, src/pickers/basic.tsx, src/types/index.ts
Bug fix. Relates to #693.
When `clearOnSameDateClick={false}`, the state is not reset properly.
The state is reset properly because `clearOnSameDateClick` is taken into account before setting `newDate` to `null`.
**Checklist**:
=> fix(datepicker): reset state properly when clearOnSameDateClick is false

package.json, src/components/input.tsx, stories/index.stories.tsx, yarn.lock
Bug fix. Closes #707.
When an input inside a `Form` has `error`, isn't styled properly.
The input is styled properly.
**Checklist**:
=> fix(datepicker): pass error prop to Form.Field

src/locales/sk-Sk.json, src/types/index.ts, stories/data.ts
=> Add Slovak locale

src/locales/ro-RO.json
I just realized the coworker that made the Romanian translation translated also two of the keys. The locale will not work without this fix, crashing the component. Please accept the change!
**Checklist**:
=> Critical fix!!! ( Romanian will not work without)
