arthurdenner/react-semantic-ui-datepickers

.all-contributorsrc, README.md, src/components/calendar/calendar.css, src/components/calendar/calendar.js, src/components/datepicker.js, stories/index.js
#1
#1
The portal can be formatted so that is pointing.
**Checklist**:
=> Calendar pointing

README.md
=> docs(README): added documentation of new props in DatePicker

src/components/datepicker.js, src/utils.js, stories/index.js
Bug fix
The inserted date is validated only on blur.
When the Enter key is pressed, the inserted date is validated.
=> fix(datepicker): Validating inserted date on Enter

src/locales/de-DE.js
=> added german translation

package.json
This PR is to update kcd-scripts, addressing the broken pipeline, caused by issue https://github.com/eslint/eslint/issues/12335.
This change fixes the pipeline.
The pipeline does not work.
The pipeline works.
**Checklist**:
=> chore: Update kcd-scripts

README.md, src/components/button.tsx, src/components/input.tsx, src/types/index.ts
code only typescript
using prop-types with typescript (??)
remove prop-types use 
**Checklist**:
=> Remove prop-types use

package.json, src/__tests__/datepicker.test.tsx, yarn.lock
Add a testing library for React components.
We don't have a way to test React components.
We are using [@testing-library/react](https://github.com/testing-library/react-testing-library).
**Checklist**:
=> test: add @testing-library/react

package.json
Feature. Breaking change.
We required the React version to be at least `16.3.0`.
We required the version to be at least `16.8.0`, which support Hooks.
This is part of the effort to update `dayzed` to v3.
**Checklist**:
=> feat(package.json): bump React version in peerDependencies

src/locales/ca-ES.json
New translation. 
New translation
No new behaviour
**Checklist**:
=> Add Catalan translation

src/locales/sv-SE.json, src/types/index.ts
Adds Swedish locale according to #2 
There is no Swedish locale support.
Has Swedish locale support.
**Checklist**:
=> Feature: Add Swedish locale

src/locales/tr-TR.json, src/types/index.ts
Feature
No Turkish language support available.
Adds Turkish language support.
**Checklist**:
=> Add Turkish language

src/locales/no-NB.json, src/types/index.ts
What kind of change does this PR introduce?
Adds Norwegian locale according to #2
What is the current behavior?
There is no Norwegian locale support
What is the new behavior?
Norwegian locale support
=> Added norwegian locale

.dockerignore, .gitignore, Dockerfile, now.json, package.json
=> ci(Now): update config to Now 2.0

src/__tests__/datepicker.test.tsx, src/components/calendar/calendar.tsx, src/index.tsx, src/pickers/base.tsx, src/pickers/range.tsx, src/pickers/utils.ts, src/utils.ts
Refactor. Update code style due to update of Prettier to 2.0.
=> refactor: fix errors reported by Prettier 2.0

src/locales/cs-CZ.json, src/types/index.ts
Feature. Replaces #206.
No Czech locale available.
New locale is available under key `cs-CZ`.
**Checklist**:
=> feat(locales): add Czech locale

src/components/input.tsx, src/types/index.ts, stories/index.stories.tsx
Bug fix. Closes #374.
When an input is required, the label isn't styled properly.
The label is styled properly.
**Checklist**:
=> fix(datepicker): pass required prop to Form.Field

.storybook/preview-body.html, README.md, src/components/calendar/calendar.tsx, src/components/cell/cell.css, src/components/cell/cell.tsx, src/components/today-button.tsx, src/index.tsx, src/types/index.ts, stories/index.stories.tsx
Feature. Closes #391.
The component doesn't look nice when inside an element with the `inverted` prop.
The component looks decent enough. There is a Storybook story to demo it.
**Checklist**:
=> feat(style): support inverted prop

.storybook/main.js, package.json, yarn.lock
=> docs: add @storybook/addon-storysource

package.json, stories/index.stories.tsx
=> fix: update React peerDependency to accept v17

package.json, src/index.tsx, yarn.lock
Bug fix. Relates to #609.
The `date` prop is overridden with [this piece of code](https://github.com/arthurdenner/react-semantic-ui-datepickers/blob/develop/src/index.tsx#L155-L164).
The provided `date` prop is always passed down.
**Checklist**:
=> fix(datepicker): pass down date prop if provided

.github/workflows/build.yml, package.json, scripts/validateLocales.js
Includes validation on translation files. Relates to #726.
The translation files are not validated, being prone to human error.
There's a simple and strict validation of translation files.
**Checklist**:
=> chore(github): validate locales in workflow

src/locales/nl-NL.json, src/types/index.ts, stories/data.ts
Add Dutch locale (#2)
**Checklist**:
=> Add Dutch locale

package.json
=> fix: support React 18
